### ISSUE TITLE
Eklenti çalışmıyor

### ISSUE THREAD

**Issue by mehmetakifsari** [4bitweb/whmcs-tckimlik#1]
Modülü denedim, fakat doğru olan TC kimlik numarasını yanlış olarak gösteriyor.

**Comment by canozokur** [comment]
kontrolu nufus cuzdaninda kayitli olan ad, soyad, dogum tarihi ve tc kimlik numarasini gonderek yapiyor eklenti. bu bilgilerin dogrulugundan emin misiniz? turkce karakterlere de dikkat etmek gerekiyor.

bir de tckimlik.nvi.gov.tr hangi verinin dogru olmadigini soylemiyor yanilmiyorsam, hata mesajini duzenlemek gerekebilir. ad/soyad veya dogum tarihi de yanlis olsa su anda modul hepsine "tc kimlik numarasi yanlis" diyor.
